const KEY="gamos_ala_ellinika_v2";const schemas={baptism:["ΒΑΠΤΙΣΗ",[["ΣΤΟΙΧΕΙΑ ΖΕΥΓΑΡΙΟΥ",["Όνομα παιδιού","Όνομα Πατέρα","Επίθετο Πατέρα","Όνομα Μητέρας","Επίθετο Μητέρας","Τηλέφωνο επικοινωνίας","Email ζευγαριού"]],["ΣΤΟΙΧΕΙΑ ΜΥΣΤΗΡΙΟΥ ΒΑΠΤΙΣΗΣ",["Ημερομηνία μυστήριου","Ώρα Μυστήριου","Εκκλησία","Περιοχή","GPS Εκκλησίας"]],["ΟΜΑΔΑ ΣΥΝΕΡΓΑΤΩΝ",["Φωτογραφία","Βίντεο"]],["ΟΙΚΟΝΟΜΙΚΑ",["Συνολικό Ποσό €","Προκαταβολή €","Υπόλοιπο Ποσό €","Υπόλοιπο Ποσού Με Την Παράδοση €"]],["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ",["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ"]],["ΣΗΜΕΙΩΣΕΙΣ",["ΣΗΜΕΙΩΣΕΙΣ"]]]],weddingBaptism:["ΓΑΜΟΣ & ΒΑΠΤΙΣΗ",[["ΣΤΟΙΧΕΙΑ ΖΕΥΓΑΡΙΟΥ",["Όνομα παιδιού","Όνομα Γαμπρού","Επίθετο Γαμπρού","Όνομα Νύφης","Επίθετο Νύφης","Τηλέφωνο επικοινωνίας","Email ζευγαριού","Περιοχή / Διεύθυνση","Προετοιμασία Νύφης □","Φωτογραφία Νύφης □","Βίντεο Νύφης □","GPS σπιτιού Νύφης","Προετοιμασία Γαμπρού □","Φωτογραφία Γαμπρού □","Βίντεο Γαμπρού □","GPS σπιτιού Γαμπρού"]],["ΣΤΟΙΧΕΙΑ ΜΥΣΤΗΡΙΟΥ ΓΑΜΟΥ & ΒΑΠΤΙΣΗΣ",["Ημερομηνία μυστήριου","Ώρα Μυστήριου","Εκκλησία","Περιοχή","GPS Εκκλησίας","Δεξίωση ΝΑΙ ΟΧΙ","Κέντρο Δεξίωσης","GPS Δεξίωσης"]],["ΟΜΑΔΑ ΣΥΝΕΡΓΑΤΩΝ",["Φωτογραφία","Βίντεο"]],["ΟΙΚΟΝΟΜΙΚΑ",["Συνολικό Ποσό €","Προκαταβολή €","Υπόλοιπο Ποσό €","Υπόλοιπο Ποσού Με Την Παράδοση €"]],["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ",["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ"]],["ΣΗΜΕΙΩΣΕΙΣ",["ΣΗΜΕΙΩΣΕΙΣ"]]]],civilWedding:["ΠΟΛΙΤΙΚΟΣ ΓΑΜΟΣ",[["ΣΤΟΙΧΕΙΑ ΖΕΥΓΑΡΙΟΥ",["Όνομα Γαμπρού","Επίθετο Γαμπρού","Όνομα Νύφης","Επίθετο Νύφης","Τηλέφωνο επικοινωνίας","Email ζευγαριού","Περιοχή / Διεύθυνση"]],["ΣΤΟΙΧΕΙΑ ΜΥΣΤΗΡΙΟΥ ΠΟΛΙΤΙΚΟΥ ΓΑΜΟΥ",["Ημερομηνία μυστήριου","Ώρα Μυστήριου","Δημαρχείο","GPS Δημαρχείου","Περιοχή"]],["ΟΜΑΔΑ ΣΥΝΕΡΓΑΤΩΝ",["Φωτογραφία","Βίντεο"]],["ΟΙΚΟΝΟΜΙΚΑ",["Συνολικό Ποσό €","Προκαταβολή €","Υπόλοιπο Ποσό €","Υπόλοιπο Ποσού Με Την Παράδοση €"]],["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ",["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ"]],["ΣΗΜΕΙΩΣΕΙΣ",["ΣΗΜΕΙΩΣΕΙΣ"]]]],wedding:["ΓΑΜΟΣ",[["ΣΤΟΙΧΕΙΑ ΖΕΥΓΑΡΙΟΥ",["Όνομα Γαμπρού","Επίθετο Γαμπρού","Όνομα Νύφης","Επίθετο Νύφης","Τηλέφωνο επικοινωνίας","Email ζευγαριού","Περιοχή / Διεύθυνση","Προετοιμασία Νύφης □","Φωτογραφία Νύφης □","Βίντεο Νύφης □","GPS σπιτιού Νύφης","Προετοιμασία Γαμπρού □","Φωτογραφία Γαμπρού □","Βίντεο Γαμπρού □","GPS σπιτιού Γαμπρού"]],["ΣΤΟΙΧΕΙΑ ΜΥΣΤΗΡΙΟΥ ΓΑΜΟΥ",["Ημερομηνία μυστήριου","Ώρα Μυστήριου","Εκκλησία","Περιοχή","GPS Εκκλησίας","Δεξίωση ΝΑΙ ΟΧΙ","Κέντρο Δεξίωσης","GPS Δεξίωσης"]],["ΟΜΑΔΑ ΣΥΝΕΡΓΑΤΩΝ",["Φωτογραφία","Βίντεο"]],["ΟΙΚΟΝΟΜΙΚΑ",["Συνολικό Ποσό €","Προκαταβολή €","Υπόλοιπο Ποσό €","Υπόλοιπο Ποσού Με Την Παράδοση €"]],["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ",["ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ"]]]]};
const KEY="gamos_ala_ellinika_v2",DAYKEY="gamos_daily_schedule_v1";
let data=[],daily={},month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
const $=id=>document.getElementById(id);
try{data=JSON.parse(localStorage.getItem(KEY)||"[]");if(!Array.isArray(data))data=[]}catch(e){data=[]}
try{daily=JSON.parse(localStorage.getItem(DAYKEY)||"{}");if(!daily||typeof daily!=="object")daily={}}catch(e){daily={}}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const todayISO=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));const v=$(id);if(v)v.classList.remove("hidden");window.scrollTo(0,0)}
function renderDaily(){const date=$("scheduleDate")?.value,rows=$("scheduleRows");if(!date||!rows)return;rows.innerHTML="";for(let h=8;h<=22;h++){const t=String(h).padStart(2,"0")+":00",row=document.createElement("div");row.className="schedule-row";row.innerHTML="<span>"+t+"</span><input type=\"text\" placeholder=\"Τι έχεις προγραμματίσει;\">";const inp=row.querySelector("input");inp.value=(daily[date]||{})[t]||"";inp.addEventListener("input",()=>{daily[date]=daily[date]||{};daily[date][t]=inp.value;localStorage.setItem(DAYKEY,JSON.stringify(daily))});rows.appendChild(row)}}
function field(q,v){if(q.endsWith("□"))return '<div class="field check '+((q.startsWith("Προετοιμασία")||q.startsWith("GPS"))?"check-full":"")+'"><label><input type="checkbox" name="'+esc(q)+'" '+(v==="ΝΑΙ"?"checked":"")+'><span>'+esc(q.replace(" □",""))+"</span></label></div>";if(q==="ΙΔΙΑΙΤΕΡΟΤΗΤΕΣ"||q==="ΣΗΜΕΙΩΣΕΙΣ")return '<div class="field full"><label>'+esc(q)+'</label><textarea name="'+esc(q)+'">'+esc(v||"")+"</textarea></div>";if(q==="Δεξίωση ΝΑΙ ΟΧΙ")return '<div class="field"><label>'+esc(q)+'</label><select name="'+esc(q)+'"><option></option><option '+(v==="ΝΑΙ"?"selected":"")+'>ΝΑΙ</option><option '+(v==="ΟΧΙ"?"selected":"")+'>ΟΧΙ</option></select></div>';const type=q.includes("Ημερομηνία")?"date":q.includes("Ώρα")?"time":q.includes("Email")?"email":q.includes("Ποσό")?"number":"text";return '<div class="field"><label>'+esc(q)+'</label><input type="'+type+'" name="'+esc(q)+'" value="'+esc(v||"")+'"></div>'}
function form(type,old){const [title,sections]=schemas[type];let v=old?.fields||{},h='<h2>'+title+'</h2><form id="mform">';sections.forEach(([sec,fs])=>{h+='<div class="form-section"><h3>'+sec+'</h3><div class="fields">';fs.forEach(q=>h+=field(q,v[q]));h+="</div></div>"});h+='<button class="primary" type="submit">💾 ΑΠΟΘΗΚΕΥΣΗ</button></form>';$("formMount").innerHTML=h;show("formView");$("mform").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target),fields={};fd.forEach((val,key)=>fields[key]=val);e.target.querySelectorAll('input[type="checkbox"]').forEach(c=>fields[c.name]=c.checked?"ΝΑΙ":"ΟΧΙ");if(!fields["Ημερομηνία μυστήριου"]){alert("Συμπλήρωσε την ημερομηνία του μυστηρίου.");return}const item={id:old?.id||crypto.randomUUID(),type,date:fields["Ημερομηνία μυστήριου"],fields};if(old)data=data.map(x=>x.id===old.id?item:x);else data.push(item);save();month=new Date(item.date+"T00:00:00");calendar();show("calendarView")})}
function eventTitle(x){const f=x.fields;if(x.type==="baptism")return "Μυστήριο Βάπτισης "+(f["Όνομα παιδιού"]||"");if(x.type==="weddingBaptism")return "Μυστήριο Γάμου & Βάπτισης "+[f["Όνομα Γαμπρού"],f["Όνομα Νύφης"]].filter(Boolean).join(" & ");return "Μυστήριο "+schemas[x.type][0]+" "+[f["Όνομα Γαμπρού"],f["Όνομα Νύφης"]].filter(Boolean).join(" & ")}
function calendar(){const y=month.getFullYear(),m=month.getMonth();$("monthTitle").textContent=new Intl.DateTimeFormat("el-GR",{month:"long",year:"numeric"}).format(month).toUpperCase();const g=$("calendar");g.innerHTML="";const first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)g.appendChild(document.createElement("div"));for(let d=1;d<=days;d++){const c=document.createElement("div");c.className="day";c.innerHTML="<b>"+d+"</b>";data.filter(x=>{const z=new Date(x.date+"T00:00:00");return z.getFullYear()===y&&z.getMonth()===m&&z.getDate()===d}).forEach(x=>{const b=document.createElement("button");b.className="event";b.type="button";b.textContent=eventTitle(x);b.addEventListener("click",()=>detail(x));c.appendChild(b)});g.appendChild(c)}}
function detail(x){const [title,sections]=schemas[x.type];let h="<h2>"+title+"</h2>";sections.forEach(([sec,fs])=>{h+='<div class="form-section"><h3>'+sec+'</h3><div class="detail-grid">';fs.forEach(q=>h+='<div class="detail"><b>'+esc(q)+"</b><br>"+esc(x.fields[q]||"—").replace(/\n/g,"<br>")+"</div>");h+="</div></div>"});h+='<button class="primary" id="edit" type="button">✏️ ΕΠΕΞΕΡΓΑΣΙΑ</button><button class="danger" id="del" type="button">🗑️ ΔΙΑΓΡΑΦΗ</button>';$("detailMount").innerHTML=h;show("detailView");$("edit").onclick=()=>form(x.type,x);$("del").onclick=()=>{if(confirm("Να διαγραφεί το μυστήριο;")){data=data.filter(a=>a.id!==x.id);save();calendar();show("calendarView")}}}
function init(){document.querySelectorAll(".type-card").forEach(b=>b.onclick=()=>form(b.dataset.type));$("newBtn").onclick=()=>show("typeView");$("calendarBtn").onclick=()=>{calendar();show("calendarView")};$("menuBtn").onclick=()=>$("sideMenu").classList.remove("hidden");$("closeMenu").onclick=()=>$("sideMenu").classList.add("hidden");$("mysteriesBtn").onclick=()=>{ $("sideMenu").classList.add("hidden");show("typeView")};document.querySelectorAll(".back").forEach(b=>b.onclick=()=>show(b.dataset.back));$("prevMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);calendar()};$("nextMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);calendar()};$("scheduleDate").value=todayISO();$("scheduleDate").onchange=renderDaily;renderDaily();calendar()}
window.show=show;window.form=form;window.calendar=calendar;window.detail=detail;
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();