/* Συγχρονισμός ΓΑΜΟΣ ΑΛΑ ΕΛΛΗΝΙΚΑ μεταξύ συσκευών */
(function(){
  const SUPABASE_URL="https://vbkuvexyqehmpeeejqbh.supabase.co";
  const SUPABASE_KEY="sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk";
  const TABLE="photographer_sync_state";
  const KEYS=["gamos_ala_ellinika_v3","gamos_daily_schedule_v2","gamos_collaborators_v1","gamos_happy_box_v1","gamos_happy_orders_v2","gamos_appointments_mysteries_v1","gamos_appointments_partners_v1"];
  let client=null,user=null,applying=false,writeTimer=null,channel=null,sessionStarting=false;
  const $=id=>document.getElementById(id);
  function setStatus(s){const el=$("cloudSyncStatus");if(el)el.textContent=s}
  function stateFromLocal(){const out={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)out[k]=v});return out}
  function applyState(payload){const old=stateFromLocal();const changed=KEYS.some(k=>(old[k]||null)!==(payload&&payload[k]!==undefined?payload[k]:null));applying=true;try{KEYS.forEach(k=>{if(payload&&Object.prototype.hasOwnProperty.call(payload,k))localStorage.setItem(k,payload[k]);else localStorage.removeItem(k)})}finally{applying=false}return changed}
  async function saveCloud(){if(!client||!user||applying)return;clearTimeout(writeTimer);writeTimer=setTimeout(async()=>{try{setStatus("Συγχρονισμός…");const {data,error}=await client.functions.invoke("photographer-sync",{body:{action:"save",payload:stateFromLocal()}});if(error)throw error;if(data&&data.error)throw new Error(data.error);setStatus("✓ Συγχρονίστηκε")}catch(e){console.error(e);setStatus("⚠ Δεν έγινε συγχρονισμός — έλεγξε τη σύνδεση")}},350)}
  function installLocalHooks(){const originalSet=localStorage.setItem.bind(localStorage),originalRemove=localStorage.removeItem.bind(localStorage);localStorage.setItem=function(k,v){originalSet(k,v);if(KEYS.includes(String(k)))saveCloud()};localStorage.removeItem=function(k){originalRemove(k);if(KEYS.includes(String(k)))saveCloud()};window.addEventListener("storage",e=>{if(KEYS.includes(e.key)&&user){if(e.newValue===null)localStorage.removeItem(e.key);else localStorage.setItem(e.key,e.newValue)}})}
  function clearAuthStorage(){Object.keys(localStorage).filter(k=>k.indexOf("-auth-token")>=0||k.startsWith("sb-")).forEach(k=>{try{localStorage.removeItem(k)}catch(e){}})}
  function showGate(){if($("cloudSyncGate"))return;const gate=document.createElement("div");gate.id="cloudSyncGate";gate.innerHTML='<div class="cloud-card"><h2>☁️ ΣΥΓΧΡΟΝΙΣΜΟΣ ΣΥΣΚΕΥΩΝ</h2><p>Συνδέσου με το email σου για να βλέπεις τα ίδια στοιχεία σε κινητό και υπολογιστή.</p><label for="cloudEmail">EMAIL</label><input id="cloudEmail" type="email" autocomplete="email" placeholder="Το email σου"><button id="cloudLogin" type="button">ΑΠΟΣΤΟΛΗ ΣΥΝΔΕΣΜΟΥ ΣΥΝΔΕΣΗΣ</button><p id="cloudMsg" role="status">Θα λάβεις email με ασφαλή σύνδεσμο. Άνοιξέ τον σε αυτή τη συσκευή.</p></div>';document.body.appendChild(gate);$("cloudLogin").onclick=async()=>{const email=$("cloudEmail").value.trim();if(!email){$("cloudMsg").textContent="Συμπλήρωσε το email σου.";return} $("cloudLogin").disabled=true;$("cloudMsg").textContent="Αποστολή…";const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$("cloudLogin").disabled=false;$("cloudMsg").textContent=error?("Σφάλμα: "+error.message):"Ο σύνδεσμος στάλθηκε. Άνοιξέ τον και περίμενε να ολοκληρωθεί η σύνδεση.";};}
  function removeGate(){const el=$("cloudSyncGate");if(el)el.remove()}
  async function startSession(session){if(sessionStarting)return;sessionStarting=true;try{user=session.user;removeGate();setStatus("Σύνδεση…");const {data,error}=await client.functions.invoke("photographer-sync",{body:{action:"load"}});if(error||data?.error){const msg=(error&&error.message)||(data&&data.error)||"άγνωστο σφάλμα";console.error("Cloud read error",error);if(/JWT issued at future/i.test(msg)){user=null;try{await client.auth.signOut({scope:"local"})}catch(e){console.warn("Could not clear expired auth",e)}clearAuthStorage();setStatus("⚠ Η σύνδεση έχει λανθασμένη ώρα ασφαλείας. Τα τοπικά στοιχεία δεν διαγράφηκαν. Συνδέσου ξανά με νέο email.");showGate();return}setStatus("⚠ Πρόβλημα ανάγνωσης cloud: "+msg);return}if(data&&data.payload){if(applyState(data.payload)){window.location.reload();return}}else{const {data:saveData,error:saveError}=await client.functions.invoke("photographer-sync",{body:{action:"save",payload:stateFromLocal()}});if(saveError||saveData?.error){console.error("Cloud initial save error",saveError||saveData);setStatus("⚠ Δεν αποθηκεύτηκαν τα αρχικά στοιχεία: "+((saveError&&saveError.message)||(saveData&&saveData.error)||"άγνωστο σφάλμα"));return}}
    setStatus("✓ Συγχρονισμός ενεργός");
  }finally{sessionStarting=false}}
  function addStyles(){const s=document.createElement("style");s.textContent="#cloudSyncGate{position:fixed;inset:0;z-index:99999;background:#f5f1e9;display:grid;place-items:center;padding:18px}.cloud-card{width:min(100%,440px);background:white;padding:28px;border-radius:18px;box-shadow:0 10px 40px #0002;text-align:center;color:#203b2d}.cloud-card h2{font-size:24px}.cloud-card p{line-height:1.5}.cloud-card label{display:block;text-align:left;font-weight:bold;margin:16px 0 6px}.cloud-card input{box-sizing:border-box;width:100%;font-size:18px;padding:14px;border:1px solid #bbb;border-radius:9px}.cloud-card button{width:100%;margin-top:14px;padding:15px;border:0;border-radius:9px;background:#24583b;color:white;font-size:16px;font-weight:bold}#cloudSyncStatus{font-size:13px;padding:5px 12px;text-align:center;color:#24583b;background:#eef5ef}";document.head.appendChild(s);const st=document.createElement("div");st.id="cloudSyncStatus";st.textContent="☁️ Έλεγχος σύνδεσης…";document.body.insertBefore(st,document.body.firstChild)}
  async function init(){addStyles();installLocalHooks();const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";script.onload=async()=>{client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"implicit"}});client.auth.onAuthStateChange((event,session)=>{if(session)Promise.resolve().then(()=>startSession(session)).catch(e=>{console.error("Session start error",e);setStatus("⚠ Η σύνδεση απέτυχε. Κάνε ανανέωση και δοκίμασε ξανά.")});else if(event==="SIGNED_OUT"){user=null;showGate();setStatus("Αποσυνδέθηκε")}});
    try{const res=await client.auth.getSession();if(res&&res.data&&res.data.session){await startSession(res.data.session);return}
      const hash=new URLSearchParams(location.hash.slice(1));const access_token=hash.get("access_token"),refresh_token=hash.get("refresh_token");
      if(access_token&&refresh_token){setStatus("Ολοκλήρωση ασφαλούς σύνδεσης…");const {data,error}=await client.auth.setSession({access_token,refresh_token});if(error)throw error;if(data.session){history.replaceState(null,"",location.pathname+location.search);await startSession(data.session);return}}
      setTimeout(()=>{if(!user){showGate();setStatus("Απαιτείται σύνδεση")}},2500)
    }catch(e){console.error("Auth callback/session error",e);setStatus("⚠ Δεν ολοκληρώθηκε η σύνδεση: "+(e.message||"δοκίμασε ξανά"));showGate()}};script.onerror=()=>{setStatus("⚠ Δεν φορτώθηκε η υπηρεσία συγχρονισμού")};document.head.appendChild(script)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();