/* Συγχρονισμός συσκευών χωρίς email */
(function(){
 const URL="https://vbkuvexyqehmpeeejqbh.supabase.co/functions/v1/photographer-device-sync";
 const API="sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk";
 const KEYS=["gamos_ala_ellinika_v3","gamos_daily_schedule_v2","gamos_collaborators_v1","gamos_happy_box_v1","gamos_happy_orders_v2","gamos_appointments_mysteries_v1","gamos_appointments_partners_v1"];
 const IDKEY="gamos_device_workspace",SECRETKEY="gamos_device_secret";
 let workspace=localStorage.getItem(IDKEY),secret=localStorage.getItem(SECRETKEY),applying=false,dirty=false,timer=null,pollTimer=null,lastUpdated="";
 const $=id=>document.getElementById(id);
 const status=s=>{const e=$("cloudSyncStatus");if(e)e.textContent=s};
 const localState=()=>{const o={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)o[k]=v});return o};
 function apply(p){applying=true;try{KEYS.forEach(k=>{if(p&&Object.prototype.hasOwnProperty.call(p,k))localStorage.setItem(k,p[k]);else localStorage.removeItem(k)})}finally{applying=false}dirty=false}
 async function call(action,payload){const r=await fetch(URL,{method:"POST",headers:{"Content-Type":"application/json","apikey":API,"Authorization":"Bearer "+API},body:JSON.stringify({action,workspace_id:workspace,secret,payload})});let d={};try{d=await r.json()}catch(e){}if(!r.ok||d.error)throw Error(d.error||("HTTP "+r.status));return d}
 function code(){return workspace+"."+secret}
 function showGate(){
  if($("deviceSyncGate"))return;
  const g=document.createElement("div");g.id="deviceSyncGate";
  g.innerHTML='<div class="device-card"><h2>☁️ ΣΥΝΤΟΝΙΣΜΟΣ ΣΥΣΚΕΥΩΝ</h2><p>Χωρίς email. Δημιούργησε προσωπικό κωδικό στην πρώτη συσκευή και χρησιμοποίησέ τον στις υπόλοιπες.</p><button id="createDeviceSync">ΔΗΜΙΟΥΡΓΙΑ ΝΕΟΥ ΣΥΝΤΟΝΙΣΜΟΥ</button><hr><label>ΕΧΩ ΗΔΗ ΚΩΔΙΚΟ ΖΕΥΞΗΣ</label><textarea id="pairingInput" placeholder="Επικόλλησε εδώ τον κωδικό από την πρώτη συσκευή"></textarea><button id="joinDeviceSync">ΣΥΝΔΕΣΗ ΑΥΤΗΣ ΤΗΣ ΣΥΣΚΕΥΗΣ</button><p id="deviceSyncMsg"></p></div>';
  document.body.appendChild(g);
  $("createDeviceSync").onclick=async()=>{const b=$("createDeviceSync");b.disabled=true;try{workspace=crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(32));secret=Array.from(bytes,x=>x.toString(16).padStart(2,"0")).join("");await call("init",localState());localStorage.setItem(IDKEY,workspace);localStorage.setItem(SECRETKEY,secret);removeGate();showPairing();status("✓ Ο συγχρονισμός δημιουργήθηκε");startPolling()}catch(e){$("deviceSyncMsg").textContent="Δεν δημιουργήθηκε: "+e.message;b.disabled=false}};
  $("joinDeviceSync").onclick=async()=>{const b=$("joinDeviceSync");b.disabled=true;try{const parts=$("pairingInput").value.trim().split(".");if(parts.length!==2||parts[0].length<20||parts[1].length<32)throw Error("Ο κωδικός δεν είναι σωστός.");workspace=parts[0];secret=parts[1];const d=await call("load");localStorage.setItem(IDKEY,workspace);localStorage.setItem(SECRETKEY,secret);if(d.payload)apply(d.payload);lastUpdated=d.updated_at||"";removeGate();status("✓ Η συσκευή συνδέθηκε");startPolling();location.reload()}catch(e){$("deviceSyncMsg").textContent="Δεν έγινε σύνδεση: "+e.message;b.disabled=false}};
 }
 function removeGate(){const e=$("deviceSyncGate");if(e)e.remove()}
 function showPairing(){if($("pairingNotice"))return;const n=document.createElement("div");n.id="pairingNotice";n.innerHTML='<div><strong>ΚΩΔΙΚΟΣ ΖΕΥΞΗΣ</strong><p>Κράτησέ τον ιδιωτικό και χρησιμοποίησέ τον στις άλλες συσκευές.</p><textarea id="pairingCode" readonly></textarea><button id="copyPairing">ΑΝΤΙΓΡΑΦΗ ΚΩΔΙΚΟΥ</button><button id="dismissPairing">ΕΝΤΑΞΕΙ</button></div>';document.body.appendChild(n);$("pairingCode").value=code();$("copyPairing").onclick=async()=>{try{await navigator.clipboard.writeText(code())}catch(e){$("pairingCode").select();document.execCommand("copy")}$("copyPairing").textContent="ΑΝΤΙΓΡΑΦΗΚΕ"};$("dismissPairing").onclick=()=>n.remove()}
 async function save(){if(!workspace||!secret||applying||!dirty)return;dirty=false;try{status("☁️ Συγχρονισμός…");const d=await call("save",localState());lastUpdated=d.updated_at||new Date().toISOString();status("✓ Τα δεδομένα συγχρονίστηκαν")}catch(e){dirty=true;status("⚠ Πρόβλημα συγχρονισμού")}}
 function schedule(){if(!workspace||applying)return;dirty=true;clearTimeout(timer);timer=setTimeout(save,500)}
 async function poll(){if(!workspace||!secret||dirty)return;try{const d=await call("load");if(d.updated_at&&d.updated_at!==lastUpdated){lastUpdated=d.updated_at;if(d.payload){apply(d.payload);status("✓ Ενημερώθηκε από άλλη συσκευή")}}}catch(e){status("⚠ Πρόβλημα συγχρονισμού")}}
 function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(poll,5000);window.addEventListener("focus",poll)}
 function styles(){const s=document.createElement("style");s.textContent="#cloudSyncStatus{font-size:14px;padding:7px 12px;text-align:center;color:#24583b;background:#eef5ef}#deviceSyncGate,#pairingNotice{position:fixed;inset:0;z-index:999999;background:#f5f1e9;display:grid;place-items:center;padding:16px;box-sizing:border-box}#pairingNotice{background:#0008}.device-card,#pairingNotice>div{box-sizing:border-box;width:min(100%,480px);max-height:90vh;overflow:auto;background:#fff;padding:24px;border-radius:18px;box-shadow:0 10px 40px #0002;color:#203b2d;text-align:center}.device-card h2{font-size:23px}.device-card p{line-height:1.5}.device-card label{display:block;text-align:left;font-weight:bold;margin:12px 0 6px}.device-card textarea,#pairingCode{box-sizing:border-box;width:100%;min-height:90px;font-size:15px;padding:12px;border:1px solid #bbb;border-radius:9px;overflow-wrap:anywhere}.device-card button,#pairingNotice button{width:100%;margin:10px 0;padding:14px;border:0;border-radius:9px;background:#24583b;color:white;font-size:15px;font-weight:bold}.device-card hr{border:0;border-top:1px solid #ddd;margin:20px 0}";document.head.appendChild(s);const e=document.createElement("div");e.id="cloudSyncStatus";e.textContent="☁️ Προετοιμασία συγχρονισμού…";document.body.insertBefore(e,document.body.firstChild)}
 function init(){styles();const set=localStorage.setItem.bind(localStorage),rem=localStorage.removeItem.bind(localStorage);localStorage.setItem=function(k,v){set(k,v);if(KEYS.includes(String(k)))schedule()};localStorage.removeItem=function(k){rem(k);if(KEYS.includes(String(k)))schedule()};if(workspace&&secret){call("load").then(d=>{if(d.payload)apply(d.payload);lastUpdated=d.updated_at||"";status("✓ Συγχρονισμός ενεργός");startPolling()}).catch(()=>{workspace=null;secret=null;localStorage.removeItem(IDKEY);localStorage.removeItem(SECRETKEY);showGate()})}else{showGate();status("☁️ Δημιούργησε ή σύνδεσε συσκευή")}}
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();